name: CI Build / Test (Push)

on:
  - push

jobs:

  build-linux:
    name: Build / Test on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build for 386
      run: GOOS=linux GOARCH=386 go build -v -x ./...

    - name: Build for ARM
      run: GOOS=linux GOARCH=arm go build -v -x ./...

    - name: Build for ARM64
      run: GOOS=linux GOARCH=arm64 go build -v -x ./...

    - name: Build for AMD64
      run: GOOS=linux GOARCH=amd64 go build -v -x ./...

    - name: Build
      run: go build -v ./...

    - name: Build (Production Mode)
      run: go build -v -tags slimcap_nomock ./...

    - name: Test
      run: |
        go test -v ./... -covermode=atomic -coverprofile=coverage.out
        go tool cover -func=coverage.out -o=coverage.out

    - name: Test (Production Mode)
      run: go test -v -tags slimcap_nomock ./...

    - name: Race Detector
      run: go test -race -v ./...
