name: CI Build / Test (Pull Request)

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  bench:
    name: Comparative Benchmark
    runs-on: [self-hosted, linux, benchmark-only]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
        show-progress: false

    - name: Run Comparative Benchmark
      id: bench
      env:
        BENCH_TORUN: .
        BENCH_COUNT: 15
        BENCH_TIME: 5s
      run: |
        printenv PATH > .path
        /home/app/bench.sh

    - name: Add / Update Benchmark Result Comment
      continue-on-error: true
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: bench
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          ### Benchmark Result
          <details><summary>Benchmark diff with base branch</summary>

          ```
          ${{ steps.bench.outputs.diff }}
          ```
          </details>
